# Linear regression

This model is [Piotrek](https://twitter.com/pkuchta)'s baseline for their [Kaggle competition](https://inclass.kaggle.com/c/predict-impact-of-air-quality-on-death-rates).

We read the training set using [Pandas](http://pandas.pydata.org)

In [ ]:
import pandas as pd

train = pd.read_csv(os.path.join('data/train.csv'), parse_dates=['date'])

The training set has the following columns:
* `Id`
* `region`
* `date`
* `mortality_rate`
* `O3`
* `PM10`
* `PM25`
* `NO2`
* `T2M`

In [ ]:
train

We have missing values for NO2 and PM25 for 2007. Simplest way of dealing with it is to remove the rows with missing values

In [ ]:
train = train.dropna(axis=0, how='any')
train

We start by training our linear regression model.

In [ ]:
features = ['O3', 'PM10', 'PM25', 'NO2', 'T2M']
X_train = train[features]
y_train = train['mortality_rate'].copy()

from sklearn.linear_model import LinearRegression
regr = LinearRegression()
regr.fit(X_train, y_train)

Our test set is like the training set above, except it does not have `mortality_rate` (that's what we're after). Ignore region and date for now.

In [ ]:
test = pd.read_csv('data/test.csv')
X_test = test[features].copy()
X_test

Let's predict!

In [18]:
predictions = test[['Id']].copy()
predictions['mortality_rate'] = regr.predict(X_test)
predictions

         Id  mortality_rate
0     18404        0.979222
1     18405        1.092495
2     18406        1.049618
3     18407        1.125773
4     18408        1.120744
5     18409        1.148282
6     18410        1.241347
7     18411        1.315640
8     18412        1.200591
9     18413        1.106845
10    18414        1.123429
11    18415        1.163742
12    18416        1.167493
13    18417        1.121565
14    18418        1.207298
15    18419        1.248390
16    18420        1.210559
17    18421        1.116369
18    18422        1.087329
19    18423        1.130248
20    18424        1.103151
21    18425        1.086978
22    18426        1.054763
23    18427        1.051473
24    18428        1.037679
25    18429        1.119119
26    18430        1.136584
27    18431        1.117165
28    18432        1.090553
29    18433        1.003954
...     ...             ...
7856  26260        1.328724
7857  26261        1.300878
7858  26262        1.362769
7859  26263        1.392801
7860  26264        1.402266
7861  26265        1.385721
7862  26266        1.430899
7863  26267        1.345586
7864  26268        1.417157
7865  26269        1.407018
7866  26270        1.365800
7867  26271        1.433476
7868  26272        1.362734
7869  26273        1.338386
7870  26274        1.339821
7871  26275        1.281167
7872  26276        1.279185
7873  26277        1.360982
7874  26278        1.380471
7875  26279        1.308902
7876  26280        1.317966
7877  26281        1.286135
7878  26282        1.350118
7879  26283        1.437661
7880  26284        1.422073
7881  26285        1.453818
7882  26286        1.482331
7883  26287        1.458679
7884  26288        1.448715
7885  26289        1.403665

[7886 rows x 2 columns]

This is the way to save the results for submission:

In [20]:
predictions.to_csv('linear_regression.csv', index=False)
!ls -l linear_regression.csv

-rw-r--r--  1 carlos  staff  157634  7 Mar 23:04 linear_regression.csv